### ISSUE TITLE
Lua erroraddons/pointshop-bodygroup/lua/ps_bodygroupselector/server/selectorenabler.lua

### ISSUE THREAD

**Issue by IFN3T** [Fafy2801/ps_bodygroupselector#1]
[ERROR] addons/pointshop-bodygroup/lua/ps_bodygroupselector/server/selectorenabler.lua:39: attempt to index local 'mods' (a nil value)
  1. SetBodygroups - addons/pointshop-bodygroup/lua/ps_bodygroupselector/server/selectorenabler.lua:39
   2. unknown - addons/pointshop/lua/pointshop/items/skins_superadmin/daobunny.lua:32
    3. fn - addons/pointshop/lua/pointshop/sh_init.lua:146
     4. Call - addons/ulib/lua/ulib/shared/hook.lua:110
      5. unknown - gamemodes/base/gamemode/player.lua:277
       6. Spawn - [C]:-1
        7. unknown - gamemodes/deathrun/gamemode/sv_player.lua:206
         8. unknown - lua/includes/modules/concommand.lua:54

**Comment by fgrg2801** [comment]
Did you put the function on `PlayerSetModel`? If so, don't. It only needs to be on `OnEquip`
Also, sorry for mega late response, GitHub doesn't send me emails for some reason

**Comment by IFN3T** [comment]
example item:

ITEM.Name = 'DAO: Bunny'
ITEM.Price = 0
ITEM.Skins = { 0 }
ITEM.Bodygroups = { 
['ID0'] = { id = 0, values = { 0, 1 } },
['ID1'] = { id = 1, values = { 0, 1 } },
['ID2'] = { id = 2, values = { 0, 1 } },
['ID3'] = { id = 3, values = { 0, 1 } },
['ID4'] = { id = 4, values = { 0, 1 } }
}
ITEM.Model = 'models/player/doa_honoka_bunny.mdl'
ITEM.AllowedUserGroups = {"superadmin"}
function ITEM:OnEquip(ply, modifications)
	if not ply._OldModel then
		ply._OldModel = ply:GetModel()
	end
	
	timer.Simple(1, function() 
	ply:SetModel(self.Model) 
	self:SetBodygroups(ply, modifications) 
	end)
end

function ITEM:OnHolster(ply)
	if ply._OldModel then
		ply:SetModel(ply._OldModel)
	end
end

function ITEM:PlayerSetModel(ply)
	ply:SetModel(self.Model)
	self:SetBodygroups(ply, modifications)
end

**Comment by fgrg2801** [comment]
Take it off `PlayerSetModel`
